
services:
  db:
    image: postgres:16
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql